###
POST http://localhost:8080/api/users/add
Content-Type: application/json

{
  "name": "国木田花丸"
}

###
POST http://localhost:8080/api/users/add/list
Content-Type: application/json

[
  {
    "name": "矢澤にこ"
  },
  {
    "name": "津島善子"
  }
]

###
POST http://localhost:8080/api/users/modify
Content-Type: application/json

{
  "id": 1,
  "name": "西木野真姫",
  "password": "12345",
  "version": 2
}

###
